_counties = [
    ("Aberdeenshire", "Aberdeenshire"),
    ("Anglesey", "Anglesey"),
    ("Angus", "Angus"),
    ("Argyll", "Argyll"),
    ("Ayrshire", "Ayrshire"),
    ("Banffshire", "Banffshire"),
    ("Bedfordshire", "Bedfordshire"),
    ("Berwickshire", "Berwickshire"),
    ("Breconshire", "Breconshire"),
    ("Buckinghamshire", "Buckinghamshire"),
    ("Bute", "Bute"),
    ("Caernarvonshire", "Caernarvonshire"),
    ("Caithness", "Caithness"),
    ("Cambridgeshire", "Cambridgeshire"),
    ("Cardiganshire", "Cardiganshire"),
    ("Carmarthenshire", "Carmarthenshire"),
    ("Cheshire", "Cheshire"),
    ("Clackmannanshire", "Clackmannanshire"),
    ("Cornwall and Isles of Scilly", "Cornwall and Isles of Scilly"),
    ("Cumbria", "Cumbria"),
    ("Denbighshire", "Denbighshire"),
    ("Derbyshire", "Derbyshire"),
    ("Devon", "Devon"),
    ("Dorset", "Dorset"),
    ("Dumbartonshire", "Dumbartonshire"),
    ("Dumfriesshire", "Dumfriesshire"),
    ("Durham", "Durham"),
    ("East Lothian", "East Lothian"),
    ("East Sussex", "East Sussex"),
    ("Essex", "Essex"),
    ("Fife", "Fife"),
    ("Flintshire", "Flintshire"),
    ("Glamorgan", "Glamorgan"),
    ("Gloucestershire", "Gloucestershire"),
    ("Greater London", "Greater London"),
    ("Greater Manchester", "Greater Manchester"),
    ("Hampshire", "Hampshire"),
    ("Hertfordshire", "Hertfordshire"),
    ("Inverness", "Inverness"),
    ("Kent", "Kent"),
    ("Kincardineshire", "Kincardineshire"),
    ("Kinross-shire", "Kinross-shire"),
    ("Kirkcudbrightshire", "Kirkcudbrightshire"),
    ("Lanarkshire", "Lanarkshire"),
    ("Lancashire", "Lancashire"),
    ("Leicestershire", "Leicestershire"),
    ("Lincolnshire", "Lincolnshire"),
    ("London", "London"),
    ("Merionethshire", "Merionethshire"),
    ("Merseyside", "Merseyside"),
    ("Midlothian", "Midlothian"),
    ("Monmouthshire", "Monmouthshire"),
    ("Montgomeryshire", "Montgomeryshire"),
    ("Moray", "Moray"),
    ("Nairnshire", "Nairnshire"),
    ("Norfolk", "Norfolk"),
    ("North Yorkshire", "North Yorkshire"),
    ("Northamptonshire", "Northamptonshire"),
    ("Northumberland", "Northumberland"),
    ("Nottinghamshire", "Nottinghamshire"),
    ("Orkney", "Orkney"),
    ("Oxfordshire", "Oxfordshire"),
    ("Peebleshire", "Peebleshire"),
    ("Pembrokeshire", "Pembrokeshire"),
    ("Perthshire", "Perthshire"),
    ("Radnorshire", "Radnorshire"),
    ("Renfrewshire", "Renfrewshire"),
    ("Ross & Cromarty", "Ross & Cromarty"),
    ("Roxburghshire", "Roxburghshire"),
    ("Selkirkshire", "Selkirkshire"),
    ("Shetland", "Shetland"),
    ("Shropshire", "Shropshire"),
    ("Somerset", "Somerset"),
    ("South Yorkshire", "South Yorkshire"),
    ("Staffordshire", "Staffordshire"),
    ("Stirlingshire", "Stirlingshire"),
    ("Suffolk", "Suffolk"),
    ("Surrey", "Surrey"),
    ("Sutherland", "Sutherland"),
    ("Tyne and Wear", "Tyne and Wear"),
    ("Warwickshire", "Warwickshire"),
    ("West Lothian", "West Lothian"),
    ("West Midlands", "West Midlands"),
    ("West Sussex", "West Sussex"),
    ("West Yorkshire", "West Yorkshire"),
    ("Wigtownshire", "Wigtownshire"),
    ("Wiltshire", "Wiltshire"),
    ("Worcestershire", "Worcestershire"),
]

def get_counties():
    return _counties
